import { ResourceDefinition } from '../models/resource.models';

export const RESOURCE_DEFINITIONS: Record<string, ResourceDefinition> = {
  users: {
    key: 'users',
    title: 'Usuarios',
    subtitle: 'Administra cuentas y accesos del personal.',
    endpoint: 'users',
    singular: 'usuario',
    roles: ['ADMINISTRADOR'],
    fields: [
      { key: 'fullName', label: 'Nombre completo', type: 'text', required: true },
      { key: 'email', label: 'Correo', type: 'email', required: true },
      {
        key: 'role',
        label: 'Rol',
        type: 'select',
        required: true,
        options: [
          { value: 'ADMINISTRADOR', label: 'Administrador' },
          { value: 'TECNICO', label: 'Técnico' },
        ],
      },
      {
        key: 'password',
        label: 'Contraseña',
        type: 'password',
        requiredOnCreateOnly: true,
        placeholder: 'Mínimo 6 caracteres',
        hideInList: true,
      },
      { key: 'phone', label: 'Teléfono', type: 'text' },
      { key: 'active', label: 'Activo', type: 'boolean', required: true },
    ],
  },
  clients: {
    key: 'clients',
    title: 'Clientes',
    subtitle: 'Gestión comercial de clientes empresariales y residenciales.',
    endpoint: 'clients',
    singular: 'cliente',
    roles: ['ADMINISTRADOR', 'TECNICO'],
    fields: [
      { key: 'nameOrBusinessName', label: 'Nombre / Razón social', type: 'text', required: true },
      { key: 'documentNumber', label: 'Documento', type: 'text', required: true },
      { key: 'phone', label: 'Teléfono', type: 'text', required: true },
      { key: 'email', label: 'Correo', type: 'email' },
      { key: 'address', label: 'Dirección', type: 'text', required: true, hideInList: true },
      { key: 'city', label: 'Ciudad', type: 'text', required: true },
      { key: 'commercialReference', label: 'Referencia comercial', type: 'text', hideInList: true },
      { key: 'observations', label: 'Observaciones', type: 'textarea' },
      { key: 'active', label: 'Activo', type: 'boolean', required: true },
    ],
  },
  suppliers: {
    key: 'suppliers',
    title: 'Proveedores',
    subtitle: 'Administración de aliados estratégicos y datos de contacto.',
    endpoint: 'suppliers',
    singular: 'proveedor',
    roles: ['ADMINISTRADOR'],
    fields: [
      { key: 'businessName', label: 'Razón social', type: 'text', required: true },
      { key: 'ruc', label: 'RUC', type: 'text', required: true },
      { key: 'contact', label: 'Contacto', type: 'text', required: true },
      { key: 'phone', label: 'Teléfono', type: 'text', required: true },
      { key: 'email', label: 'Correo', type: 'email' },
      { key: 'address', label: 'Dirección', type: 'text', required: true, hideInList: true },
      { key: 'city', label: 'Ciudad', type: 'text', required: true },
      { key: 'active', label: 'Activo', type: 'boolean', required: true },
    ],
  },
  'product-categories': {
    key: 'product-categories',
    title: 'Categorías de Productos',
    subtitle: 'Clasifica el inventario técnico y comercial.',
    endpoint: 'product-categories',
    singular: 'categoría de producto',
    roles: ['ADMINISTRADOR'],
    fields: [
      { key: 'name', label: 'Nombre', type: 'text', required: true },
      { key: 'description', label: 'Descripción', type: 'textarea' },
      { key: 'active', label: 'Activo', type: 'boolean', required: true },
    ],
  },
  products: {
    key: 'products',
    title: 'Productos',
    subtitle: 'Catálogo de equipos, materiales y stock de seguridad.',
    endpoint: 'products',
    singular: 'producto',
    roles: ['ADMINISTRADOR'],
    fields: [
      {
        key: 'categoryId',
        label: 'Categoría',
        type: 'select',
        required: true,
        endpoint: 'product-categories',
        optionLabelKey: 'name',
      },
      {
        key: 'mainSupplierId',
        label: 'Proveedor principal',
        type: 'select',
        endpoint: 'suppliers',
        optionLabelKey: 'businessName',
      },
      { key: 'internalCode', label: 'Código interno', type: 'text', required: true },
      { key: 'name', label: 'Nombre', type: 'text', required: true },
      { key: 'brand', label: 'Marca', type: 'text', required: true },
      { key: 'model', label: 'Modelo', type: 'text' },
      { key: 'description', label: 'Descripción', type: 'textarea', required: true, hideInList: true },
      { key: 'baseCost', label: 'Costo base', type: 'number', required: true },
      { key: 'stock', label: 'Stock', type: 'number', hideInList: true },
      { key: 'unit', label: 'Unidad', type: 'text', required: true },
      { key: 'imageUrl', label: 'Imagen', type: 'text' },
      { key: 'active', label: 'Activo', type: 'boolean', required: true, hideInList: true },
    ],
  },
  'service-categories': {
    key: 'service-categories',
    title: 'Categorías de Servicios',
    subtitle: 'Agrupa servicios de instalación y soporte técnico.',
    endpoint: 'service-categories',
    singular: 'categoría de servicio',
    roles: ['ADMINISTRADOR'],
    fields: [
      { key: 'name', label: 'Nombre', type: 'text', required: true },
      { key: 'description', label: 'Descripción', type: 'textarea' },
      { key: 'active', label: 'Activo', type: 'boolean', required: true },
    ],
  },
  services: {
    key: 'services',
    title: 'Servicios',
    subtitle: 'Gestión del portafolio de mano de obra y soporte.',
    endpoint: 'services',
    singular: 'servicio',
    roles: ['ADMINISTRADOR'],
    fields: [
      {
        key: 'categoryId',
        label: 'Categoría',
        type: 'select',
        required: true,
        endpoint: 'service-categories',
        optionLabelKey: 'name',
      },
      { key: 'name', label: 'Nombre', type: 'text', required: true },
      { key: 'description', label: 'Descripción', type: 'textarea', required: true },
      { key: 'baseCost', label: 'Costo base', type: 'number', required: true },
      { key: 'active', label: 'Activo', type: 'boolean', required: true },
    ],
  },
};
